services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    command: node server.js

  frontend:
    build:
      context: ./frontend/spotilike
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
